---
- name: Deploy VM with environments
  hosts: "{{ user_input }}"
  gather_facts: no
  vars_files:
    inventory/group_vars/resource.yml
  tasks:
    - name: Deploy VM
      include_role:
          role: deploy_vm
