---
- name: Deploy Server
  hosts: localhost
  gather_facts: false
  become: yes
  vars_files:
    vars/vcsa.yml
  tasks:
    - name: Deploy VCSA Appliance
      include_role:
        name: deploy_vcsa
