name: Deploy on separate environments
on: 
    workflow_dispatch:
        inputs:
          Environments:
             type: choice
             description: 'Environments:'
             required: true
             options:
             - staging
             - production
jobs:
    build:
      runs-on: [self-hosted]
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Request Deployment Approval
        if: ${{ github.event.inputs.Environment == 'production' }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            # Replace with the GitHub username of the user you want to request a review from
            review_user="xuongdon-iij"
            
            # Use the GitHub API to request a review from the specified user
            curl -X POST \
              -H "Authorization: token ${GITHUB_TOKEN}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PULL_REQUEST}/requested_reviewers" \
              -d "{\"reviewers\":[\"${review_user}\"]}"
       
      - name: Run Ansible to VM of selected evironment
        if: ${{ github.event.inputs.Environments == 'staging' || success() }}
        run: |
            if [[ "${{ github.event.inputs.Environments }}" == "staging" || "${{ github.event.inputs.Environments }}" == "production" ]]; then
                echo "Deploying to ${{ github.event.inputs.Environments }} environment..."
                ansible-playbook \
                -e "user_input=${{ github.event.inputs.Environments }}" \
                -e "VCENTER_TOKEN=${{ secrets.VCENTER_TOKEN }}" \
                -e "NESTED_VC_TOKEN=${{ secrets.NESTED_VC_TOKEN }}" \
                -e "SEFL_HOST_TOKEN=${{ secrets.SEFL_HOST_TOKEN }}" \
                -i Ansible/Deploy_envinronments/inventory/inventory.ini \
                Ansible/Deploy_envinronments/run.yml
            fi
