name: Get pull number
on: workflow_dispatch
jobs:    
    build:
      runs-on: [self-hosted]
      steps:
      - name: Get Pull Request Number
        id: get_pr_number
        run: |
            if [[ -n "${{ github.event.pull_request.number }}" ]]; then
              echo "Pull Request Number: ${{ github.event.pull_request.number }}"
            else
              echo "Pull Request Number not available. Using default."
              echo "::set-output name=PR_NUMBER::default_value"
            fi
